spring.application.name=SpringBoot-Backend-SDP-Project

server.port=${PORT:8080}
server.address=0.0.0.0

#connection properties
spring.datasource.url=jdbc:mysql://${MYSQLHOST:switchback.proxy.rlwy.net}:${MYSQLPORT:22354}/${MYSQLDATABASE:railway}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:FmCidviXXoptVkKxsdpbzAhMUFHsgDHj}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#hibernate properties

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#logging.level.root=DEBUG

#spring mail properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:adiasureshk@gmail.com}
spring.mail.password=${MAIL_PASSWORD:bayc pqsy owvt kjcy}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# JWT Secret
jwt.secret=${JWT_SECRET:MySuperStrongSecretKeyForJWT2026KlefFSDVijayawada@1234567890ABCDEF}